node {
    stage('Checkout - Dataservice') {
        git url: 'https://github.com/Lunatunny/MicroDatabase.git'
    }
    
    stage('Gradle Build - Dataservice') {
        sh 'gradle build -x test'
    }
    
    stage ('Gradle Bootjar - Package - Dataservice'){
        sh 'gradle bootjar'
    }
    
    stage ('User Acceptance Test - Dataservice'){
    	def response = input message: 'Is this build good for release?',
    	parameters: [choice(choices: 'Yes\nNo',
    	description: '', name: 'Pass')]
    	
    	if(response=='Yes') {
    		stage('Release - Dataservice') {
    			bat 'gradle build'
    		}
    	}
    }
}